name: sleepfox
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  audio_video_progress_bar: ^0.10.0
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.1.17
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.1
  get: ^4.6.5
  just_audio: ^0.9.24
  just_audio_background: ^0.0.1-beta.5
  wakelock: ^0.6.1+2
  file_picker: ^4.6.1
  cached_firestorage: ^0.1.3+1

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/icon/icon-flat-bg.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/landing_page/
    - assets/main_page/
    - assets/gallery/
    - assets/music/
    - assets/sounds/
    - assets/profile/

  fonts:
    - family: Josefin Sans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
        - asset: fonts/JosefinSans-Light.ttf
          weight: 300
        - asset: fonts/JosefinSans-Regular.ttf
          weight: 500
        - asset: fonts/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: fonts/JosefinSans-Bold.ttf
          weight: 700
